[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
select = ["E", "F", "I"]
[tool.ruff.per-file-ignores]
"__init__.py" = ["F403"]
"mysterio/settings/*.py" = ["F403", "F405", "E402"]
"asgi.py" = ["E402"]

[tool.pyright]
reportGeneralTypeIssues = false
reportOptionalMemberAccess = false
