# Generated by Django 3.2.25 on 2025-05-28 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouproomdata',
            name='admins',
            field=models.ManyToManyField(related_name='accessible_group_rooms', related_query_name='accessible_group_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouproomdata',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_rooms', related_query_name='group_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouproomdata',
            name='likers',
            field=models.ManyToManyField(related_name='favorite_rooms', related_query_name='favorite_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouproomdata',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_data', to='chat.room'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='channel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.channel'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', related_query_name='chat_session', to='sessions.session'),
        ),
        migrations.AddField(
            model_name='channel',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', related_query_name='channel', to='chat.room'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(check=models.Q(('name__in', ['YT'])), name='valid_name_choice'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(check=models.Q(('state__in', [-1, 0, 1, 2, 3, 5])), name='valid_state_choice'),
        ),
    ]
