# Generated by Django 3.2.3 on 2021-05-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouproom",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$260000$TglonmEw9G1QhxPVMaM4ux$S/Nu3ydQWhKzZADi8fxfNFMMJusvwpWwisq5RVozczo=",
                max_length=128,
            ),
        ),
    ]
