# Generated by Django 3.2.11 on 2022-02-03 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sessions", "0001_initial"),
        ("chat", "0002_auto_20220203_2253"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_sessions",
                related_query_name="chat_session",
                to="sessions.session",
            ),
        ),
    ]
