# Generated by Django 3.2.8 on 2021-10-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_grouproom_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouproom",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$260000$fZYpp9OzOMsGHsgCGE3aX3$b+qaLwgQszIW7pJ5B9IXUQODRAi0oAqI/RwYT5YQnrI=",
                max_length=128,
            ),
        ),
    ]
