# Generated by Django 3.1.1 on 2020-10-31 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sessions", "0001_initial"),
        ("chat", "0002_auto_20201031_2229"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupchannel",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sessions.session",
            ),
        ),
        migrations.AlterField(
            model_name="individualchannel",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sessions.session",
            ),
        ),
    ]
