# Generated by Django 3.1.1 on 2020-10-31 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_auto_20201031_2331"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="individualchannel",
            name="individual_channel_index",
        ),
    ]
