# Generated by Django 3.2.11 on 2022-02-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_chatsession_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="tab_session_id",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
