# Generated by Django 3.2.12 on 2022-02-05 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0004_chatsession_tab_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouproom",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_rooms",
                related_query_name="group_room",
                to="customauth.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grouproom",
            name="likers",
            field=models.ManyToManyField(
                related_name="favorite_rooms",
                related_query_name="favorite_room",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="grouproom",
            name="admins",
            field=models.ManyToManyField(
                related_name="accessible_group_rooms",
                related_query_name="accessible_group_room",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
