# Generated by Django 3.2.8 on 2021-10-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_grouproom_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouproom",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$260000$QHuo9qMFSUCGc01Kuz4D8n$df4Q7SMbSw06IbNbE3COKsl4phvLSMzBWkwSoTHpfY4=",
                max_length=128,
            ),
        ),
    ]
