# Generated by Django 3.2.12 on 2022-02-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_chatsession_tab_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="pub_key",
            field=models.CharField(default="", max_length=2000),
            preserve_default=False,
        ),
    ]
