# Generated by Django 3.2.12 on 2022-02-20 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_auto_20220206_0328"),
        ("chat", "0005_auto_20220220_2039"),
    ]

    operations = []
