# Generated by Django 3.2.8 on 2021-10-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_grouproom_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouproom",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$260000$j0WqowpH8k74FzE8CbYLzX$cBwzVv5K44kpIcPAFvX9UwiXzokqzS/lZcW0ytqb4ss=",
                max_length=128,
            ),
        ),
    ]
