# Generated by Django 3.2.12 on 2022-02-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("chat", "0006_merge_0005_auto_20220206_0328_0005_auto_20220220_2039"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="message",
            unique_together={("content_type", "object_id")},
        ),
    ]
