# Generated by Django 3.2.8 on 2021-10-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_grouproom_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouproom",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$260000$mm0GATshZRJW13CEkwmpAB$FsVtuR5uSUS1dajft+gfYqR66sHTncMvCFUiLeA0GDo=",
                max_length=128,
            ),
        ),
    ]
