# Generated by Django 3.2.8 on 2021-11-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_alter_grouproom_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouproom",
            name="is_protected",
        ),
        migrations.AlterField(
            model_name="grouproom",
            name="password",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
