# Generated by Django 3.2.12 on 2022-03-01 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_alter_message_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="group_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                related_query_name="message",
                to="chat.grouproom",
            ),
        ),
    ]
