# Generated by Django 3.2.9 on 2021-11-04 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_auto_20211103_1302"),
    ]

    operations = [
        migrations.DeleteModel(
            name="IndividualRoom",
        ),
    ]
