# Generated by Django 3.2.12 on 2022-03-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_alter_individualroom_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="state",
            field=models.SmallIntegerField(
                choices=[
                    (-1, "unstarted"),
                    (0, "ended"),
                    (1, "playing"),
                    (2, "paused"),
                    (3, "buffering"),
                    (5, "video cued"),
                ],
                default=-1,
            ),
        ),
    ]
