# Generated by Django 3.1.1 on 2020-10-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_auto_20201101_0009"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="individualchannel",
            index=models.Index(
                fields=["is_matched", "created_at"], name="individual_channel_index"
            ),
        ),
    ]
