# Generated by Django 3.2.12 on 2022-03-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chatsession_pub_key"),
        ("chat", "0010_alter_player_state"),
    ]

    operations = []
