# Generated by Django 4.0.5 on 2022-07-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_alter_player_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouproom",
            name="description",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
