# Generated by Django 4.0.5 on 2022-07-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_grouproom_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupchannel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
