# Generated by Django 3.2.12 on 2022-03-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_merge_20220311_1938"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupchannel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
