# Generated by Django 3.2.23 on 2023-11-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_player_host'),
        ('chat', '0012_groupchannel_is_active'),
    ]

    operations = [
    ]
