# Generated by Django 3.2.13 on 2023-09-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_player_host'),
        ('chat', '0012_groupchannel_is_active'),
    ]

    operations = [
    ]
