# Generated by Django 3.2.21 on 2023-10-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_merge_20230930_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='grouproom',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='grouproom',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='individualroom',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
