# Generated by Django 3.2.23 on 2023-11-04 17:43

import chat.models.message
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('chat', '0013_merge_20231104_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRoomMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.IntegerField()),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualRoomMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.IntegerField()),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualRoomTextData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=65535)),
            ],
            options={
                'abstract': False,
            },
            bases=(chat.models.message.MessageMixin, models.Model),
        ),
        migrations.RenameModel(
            old_name='TextData',
            new_name='GroupRoomTextData',
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='message',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='group_room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_channel',
        ),
        migrations.RemoveIndex(
            model_name='individualchannel',
            name='individual_channel_index',
        ),
        migrations.RemoveField(
            model_name='groupchannel',
            name='group_room',
        ),
        migrations.RemoveField(
            model_name='individualchannel',
            name='is_matched',
        ),
        migrations.RemoveField(
            model_name='individualroom',
            name='channel1',
        ),
        migrations.RemoveField(
            model_name='individualroom',
            name='channel2',
        ),
        migrations.AddField(
            model_name='groupchannel',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='channels', related_query_name='channel', to='chat.grouproom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualchannel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='individualchannel',
            name='room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channels', related_query_name='channel', to='chat.individualroom'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='groupchannel',
            name='chat_session',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatsession'),
        ),
        migrations.AlterField(
            model_name='grouproom',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='grouproom',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='individualchannel',
            name='chat_session',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatsession'),
        ),
        migrations.AlterField(
            model_name='individualroom',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='individualchannel',
            index=models.Index(condition=models.Q(('room__isnull', True)), fields=['room', 'created_at'], name='individual_channel_index'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='individualroommessage',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='individualroommessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', related_query_name='message', to='chat.individualroom'),
        ),
        migrations.AddField(
            model_name='individualroommessage',
            name='sender_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', related_query_name='message', to='chat.individualchannel'),
        ),
        migrations.AddField(
            model_name='grouproommessage',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='grouproommessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', related_query_name='message', to='chat.grouproom'),
        ),
        migrations.AddField(
            model_name='grouproommessage',
            name='sender_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', related_query_name='message', to='chat.groupchannel'),
        ),
        migrations.AlterUniqueTogether(
            name='individualroommessage',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='grouproommessage',
            unique_together={('content_type', 'object_id')},
        ),
    ]
