# Generated by Django 3.2.23 on 2023-11-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20231104_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualchannel',
            name='is_active',
        ),
    ]
