# Generated by Django 3.2.23 on 2023-11-06 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_remove_individualchannel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualchannel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='individualroommessage',
            name='sender_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', related_query_name='message', to='chat.individualchannel'),
        ),
    ]
