# Generated by Django 3.2.23 on 2023-11-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_auto_20231110_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouproomdata',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_data', related_query_name='room_data', to='chat.room'),
        ),
    ]
