# Generated by Django 3.1.1 on 2020-10-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0018_auto_20201101_0028"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="individualchannel",
            name="individual_channel_index",
        ),
    ]
