# Generated by Django 3.1.1 on 2020-11-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0021_auto_20201101_1501"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="individualchannel",
            index=models.Index(
                condition=models.Q(is_matched=False),
                fields=["created_at"],
                name="individual_channel_index1",
            ),
        ),
    ]
