# Generated by Django 3.1.3 on 2020-11-21 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sessions", "0001_initial"),
        ("chat", "0024_auto_20201101_1505"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="individualchannel",
            name="individual_channel_index1",
        ),
        migrations.RemoveIndex(
            model_name="individualchannel",
            name="individual_channel_index2",
        ),
        migrations.AlterField(
            model_name="groupchannel",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sessions.session"
            ),
        ),
        migrations.AlterField(
            model_name="individualchannel",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sessions.session"
            ),
        ),
        migrations.AddIndex(
            model_name="individualchannel",
            index=models.Index(
                condition=models.Q(is_matched=False),
                fields=["is_matched", "created_at"],
                name="individual_channel_index",
            ),
        ),
    ]
