# Generated by Django 3.1.4 on 2021-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0025_auto_20201122_0334"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouproom",
            name="zscore",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
