# Generated by Django 3.2.3 on 2021-05-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0027_alter_grouproom_zscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="textmessage",
            name="message_type",
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
