# Generated by Django 3.2.3 on 2021-05-26 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0029_auto_20210525_2007"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouproom",
            name="admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grouproom",
            name="password",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
