# Generated by Django 3.2.3 on 2021-05-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0031_auto_20210526_2244"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouproom",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$260000$PHrI9V96H9XJkusn5Pah24$akXQ8FwUFOmNwZRTXmKsm56c6jIFbbhVHeF3Z0DNqO4=",
                max_length=128,
            ),
        ),
    ]
