# Generated by Django 3.2.3 on 2021-05-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0032_alter_grouproom_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouproom",
            name="is_protected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="grouproom",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$260000$keItuDQYkXgr1XFrCSxJxg$TC/iPAKHqVPvHk3rQM50U+67ll7fy7YxAtDfDhs9i9w=",
                max_length=128,
            ),
        ),
    ]
