export const ProfileActions = Object.freeze({
  HYDRATED: 'PROFILE/HYDRATED',
  BASIC_INFO_UPDATED: 'PROFILE/BASIC_INFO_UPDATED',
});

export const UserActions = Object.freeze({
  LOGIN_SUCCEEDED: 'USER/LOGIN_SUCCEEDED',
  LOGGED_OUT: 'USER/LOGGED_OUT',
  HYDRATED: 'USER/HYDRATED',
});

export const AlertActions = Object.freeze({
  ADDED: 'ALERT/ADDED',
  REMOVED: 'ALERT/REMOVED',
});

export const WaitScreenActions = Object.freeze({
  STARTED: 'WAITSCREEN/STARTED',
  ENDED: 'WAITSCREEN/ENDED',
});

export const GlobalDialogActions = Object.freeze({
  OPENED: 'GLOBALDIALOG/OPENED',
  CLOSED: 'GLOBALDIALOG/CLOSED',
});

export const ChatInfoActions = Object.freeze({
  STATUS_UPDATED: 'CHATINFO/STATUS_UPDATED',
  INITIALIZED: 'CHATINFO/INITIALIZED',
});

export const ChatRoomInfoActions = Object.freeze({
  ROOM_DATA_UPDATED: 'CHATROOMINFO/ROOM_DATA_UPDATED',
  BASIC_INFO_UPDATED: 'CHATROOMINFO/BASIC_INFO_UPDATED',
});

export const ChatRoomDataActions = Object.freeze({
  INITIALIZED: 'CHATROOMDATA/INITIALIZED',
  ADMIN_ACCESS_UPDATED: 'CHATROOMDATA/ADMIN_ACCESS_UPDATED',
  FAVORITE_STATUS_UPDATED: 'CHATROOMDATA/FAVORITE_STATUS_UPDATED',
});

export const ChatMessageActions = Object.freeze({
  MESSAGE_ADDED: 'CHATMESSAGE/MESSAGE_ADDED',
  PREVIOUS_MESSAGES_ADDED: 'CHATMESSAGE/PREVIOUS_MESSAGES_ADDED',
});
