export const ProfileActions = Object.freeze({
  SET_NAME: 'PROFILE/SET_NAME',
  SET_AVATAR_URL: 'PROFILE/SET_AVATAR_URL',
  SET_SESSION_ID: 'PROFILE/SET_SESSION_ID',
  SET_EMAIL: 'PROFILE/SET_EMAIL',
  SET_PROFILE_INITIALIZED: 'PROFILE/SET_PROFILE/INITIALIZED',
  SET_SOCIAL: 'PROFILE/SET_SOCIAL',
  SET_BASIC_INFO: 'PROFILE/SET_BASIC_INFO',
  LOGIN: 'PROFILE/LOGIN',
  LOGOUT: 'PROFILE/LOGOUT',
});

export const AlertActions = Object.freeze({
  SHOW: 'ALERT/SHOW',
  HIDE: 'ALERT/HIDE',
});
